Lesson 19: Rack-Interface
georgiybykov/time-getter-rack-app pull request #1
Opened 2021-01-29 01:08 UTC by georgiybykov

В отдельном резпозитории напишите минималистичное `Rack` приложение, которое будет отвечать на:
```
URL GET /time
```
с параметром строки запроса `format` и возвращать время в заданном формате. 

Например, `GET-запрос`:
```
/time?format=year%2Cmonth%2Cday
```
вернет ответ с типом `text/plain` и телом `1970-01-01`.

- **Доступные форматы времени:** year, month, day, hour, minute, second.
- Форматы передаются в параметре строки запроса `format` в любом порядке.
- Если среди форматов времени присутствует неизвестный формат, необходимо возвращать **ответ с кодом статуса 400** и **телом** `"Unknown time format [epoch]".`
- Если неизвестных форматов несколько, все они должны быть перечислены в теле ответа, например: `"Unknown time format [epoch, age]"`.
- При **запросе на любой другой URL** необходимо возвращать **ответ с кодом статуса 404**.

Ответ к заданию должен быть в виде открытого пулл-реквеста.

2021-01-29 19:23 UTC, VidgarVii requested changes

2021-01-29 19:23 UTC, VidgarVii commented on config.ru
> +use Dispathcer
вместо самописного Dispathcer можно использовать Rack::URLMap

2021-01-29 19:23 UTC, VidgarVii commented on config.ru
> +require_relative 'lib/params_formatter'
так как у тебя нет модуля отвечающий за загрузку зависимостей. То лучше загружать файлы там где это требуется) Есть шанс, что в каких то ситуациях файл может не пригодиться. И это придаст явность. Но опять же обычно пишут класс который всё подключает. (не требуется в этом ДЗ. Тут он будет оверхед)

2021-01-29 19:23 UTC, VidgarVii commented on app.rb
> +    { 'Content-Type' => 'text/plain' }
так как он задаётся по умолчанию. тут опять же можно воспользоваться инструментами rack
Rack::ContentType https://www.rubydoc.info/gems/rack/Rack/ContentType

2021-01-29 19:23 UTC, VidgarVii commented on app.rb
> +    [status, headers, body]
есть готовое решение Rack::Response https://www.rubydoc.info/gems/rack/Rack/Response

2021-01-29 19:23 UTC, VidgarVii commented on app.rb
> +    formatted_params.errors.empty? ? 200 : 400
200 : 400 магические числа. 
они должны лежать в константе. И хорошо бы тут использовать именованные ключи, formatted_params.errors.empty? ? HTTP_STATUS[:ok] : HTTP_STATUS[:bad_request]

можно воспользоваться готовым списком  Rack::Utils::HTTP_STATUS_CODES

2021-01-29 19:23 UTC, VidgarVii commented on lib/params_formatter.rb
> +    query.split('=')[-1].split('%2C')
по таблице ASCII 2C это **,** =)
чтобы корректно парсить реквест, опять же лучше воспользоваться готовым решением

Rack::Utils.parse_nested_query(request.query_string)

где request это объект Rack::Request.new(env)

c готовыми объектами всегда работать приятней)

2021-01-29 19:23 UTC, VidgarVii commented on lib/params_formatter.rb
> +    query.split('=')[-1].split('%2C')
а если это задача rack, то подобному коду в этом классе не место

2021-01-31 01:00 UTC, georgiybykov commented on app.rb
> +    formatted_params.errors.empty? ? 200 : 400
```
  def status
    status = Rack::Utils::HTTP_STATUS_CODES

    formatted_params.errors.empty? ? status.key('OK') : status.key('Bad Request')
  end
```

2021-01-31 01:11 UTC, georgiybykov commented on lib/params_formatter.rb
> +    query.split('=')[-1].split('%2C')
Исправил)

Вместо:
```
@request = Rack::Request.new(env)
@params = Rack::Utils.parse_nested_query(@request.query_string)
```
Можно использовать:
```
@request = Rack::Request.new(env)
@params = @request.params
```
->
```
@request = Rack::Request.new(env)
p @request.query_string                                   #=> "format=year%2Cmonth%2Cday%2Chour%2Cminute%2Csecond"
p Rack::Utils.parse_nested_query(@request.query_string)   #=> {"format"=>"year,month,day,hour,minute,second"}
p @request.params                                         #=> {"format"=>"year,month,day,hour,minute,second"}

```

2021-01-31 02:18 UTC, georgiybykov commented on app.rb
> +    { 'Content-Type' => 'text/plain' }
Спасибо

2021-01-31 02:18 UTC, georgiybykov commented on app.rb
> +    [status, headers, body]
Спасибо, полезная информация

2021-01-31 02:44 UTC, georgiybykov commented on config.ru
> +use Dispathcer
Спасибо за совет)

2021-02-01 21:58 UTC, merged